name: Autograding Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read

  
jobs:
  feedback:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Download the solution script from the release
    - name: Download solution script from release
      run: |
        curl -L -o solution.sh "https://github.com/TU-COSC-Dierbach/Fall2024-Practicum-01-Repo/releases/download/v1.0/solution.sh"
        chmod +x solution.sh  # Make it executable

    # Debug to verify the solution script
    - name: Debug solution script
      run: |
        ls -la solution.sh
        cat solution.sh || echo "solution.sh not found or empty"

    - name: Scanner_test
      id: scanner_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Scanner_test
        setup-command: |
          javac main.java || exit 1  # Compile the code
        command: bash solution.sh
        timeout: 10
        max-score: 5

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SCANNER_TEST_RESULTS: "${{steps.scanner_test.outputs.result}}"
      with:
        runners: scanner_test
