name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Compilation Test
      id: compilation-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Compilation Test
        setup-command: ''
        command: "./Tests/javac main.java"
        timeout: 1
        max-score: 0
    - name: Practicum1test
      id: practicum1test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Practicum1test
        setup-command: ''
        command: gradle test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COMPILATION-TEST_RESULTS: "${{steps.compilation-test.outputs.result}}"
        PRACTICUM1TEST_RESULTS: "${{steps.practicum1test.outputs.result}}"
      with:
        runners: compilation-test,practicum1test
