name: Autograding Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read


jobs:
  feedback:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check for scanner
      id: scanner_check 
      run: | 
        if grep -q 'java.util.Scanner input = new java.util.Scanner(System.in);' main.java; then 
        echo "scanner_points=5" >> $GITHUB_ENV 
        else 
        echo "scanner_points=0" >> $GITHUB_ENV 
        exit 1 
        fi 

    - name: Scanner_test
      id: scanner_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Scanner_test
        setup-command: |
          javac main.java || exit 1
        command: |
          if [ "$scanner_points" -eq 5 ]; then
            exit 0
          else
            exit 1
          fi
          # if grep -q 'java.util.Scanner input = new java.util.Scanner(System.in);' main.java; then
          #     exit 0  
          # else
          #     exit 1
          # fi

        timeout: 10
        max-score: 5

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SCANNER_TEST_RESULTS: "${{steps.scanner_test.outputs.result}}"
      with:
        runners: scanner_test