name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
     - name: Checkout repository
        uses: actions/checkout@v2

    - name: Check for Scanner usage
      id: scanner_check
      run: |
        if grep -q "Scanner input = new Scanner(System.in);" Main.java; then
            echo "Correct Scanner usage detected."
            echo "score=5" >> $GITHUB_ENV  # Full points for correct usage
        elif grep -q "java.util.Scanner input = new java.util.Scanner(System.in);" Main.java; then
            echo "Scanner usage detected, but with full package name."
            echo "score=5" >> $GITHUB_ENV  # Also counts as full points
        else
            echo "Scanner usage not detected."
            echo "score=0" >> $GITHUB_ENV  # No points
        fi

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: scanner
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure to use the GitHub token
        env:
          SCANNER_RESULTS: ${{ env.score }}  # Pass the score
    # - name: Autograding Reporter
    #   uses: classroom-resources/autograding-grading-reporter@v1
      # For more information on this runner, see the documentation at https://github.com/classroom-resources/autograding-grading-reporter
      # To output the results of the tests, you can use the
      # autograding-grading-reporter action like this:
      # env:
      # ADDITION-TEST_RESULTS: "${{ steps.addition - test.outputs.result }}"
      #     with:
      #         runners: addition-test